services:
  - type: web
    name: veritrail-audit-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: veritrail-audit-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://veritrail-audit-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
